# Generated by Django 6.0.7 on 2026-07-20 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Comm.'), ('ME', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('BCA_MCA', 'BCA / MCA'), ('COMMERCE', 'Commerce & Business'), ('OTHER', 'General / Other')], default='CSE', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('DBMS', 'DBMS'), ('OS', 'Operating System'), ('CN', 'Computer Networks'), ('CC', 'Cloud Computing'), ('DSA', 'Data Structures'), ('JAVA', 'Java'), ('PYTHON', 'Python'), ('MATH', 'Mathematics'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'note')},
            },
        ),
    ]
