# Generated by Django 6.0.7 on 2026-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text or markdown content for online created e-notes'),
        ),
        migrations.AddField(
            model_name='note',
            name='is_online_note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
