# Generated by Django 6.0.7 on 2026-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_content_note_is_online_note_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='drawing_data',
            field=models.TextField(blank=True, help_text='Base64 canvas drawing image data'),
        ),
    ]
