# Generated by Django 6.0.7 on 2026-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
